server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: SH
        namespace: b12e45b6-314e-4fa7-bf6d-08a7a532b3ed # dev
  application:
    name: userservice
#      discovery:
#        cluster-name: SH
#        ephemeral: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
pattern:
  name: 本地name
#  pattern:
#    dateformat: MM-dd HH:mm:ss:SSS
#userservice: # 给某个微服务配置负载均衡规则，这里是userservice服务
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡规则